/**
 * A QR code, rendered as inline SVG.
 *
 * Three decisions worth recording, because each has an obvious alternative that
 * is wrong for this tool:
 *
 *  - **SVG, inlined, not an `<img>` with a data URI.** A code at an event is
 *    either projected or printed, and both want vectors. The encoder in
 *    `core/qr.ts` deliberately writes `var(--qr-ink)` and `var(--qr-paper)`
 *    rather than hex fills, and a custom property does not cross into an
 *    externally referenced SVG document. Inlining is what makes the themed
 *    pairing work at all.
 *  - **`dangerouslySetInnerHTML` is the honest way to do that.** The string is
 *    built by our own encoder from a module matrix; nothing from `value`
 *    reaches the markup, and the only interpolated numbers are the symbol's
 *    size and version. Rebuilding the path as React elements would mean a
 *    second copy of the run-length loop, which is more code and no more safe.
 *  - **The capacity verdict is shown, not swallowed.** A Version 30 symbol
 *    still renders on a laptop screen and still fails from the back of a room,
 *    so the one case where the encoder has something to say gets said.
 */
import { useMemo, type ReactNode } from 'react';
import { encodeShlQr, type QrEncodeResult } from '../core/qr';
import { Callout } from './primitives';

export interface QrCodeProps {
  /** The exact text the code carries. For a link, that is the link verbatim. */
  value: string;
  /** Rendered width in CSS pixels. The symbol is vector, so this is a hint. */
  size?: number | undefined;
  /** A line naming what the code carries, above the symbol's own metadata. */
  caption?: ReactNode;
}

type Encoded = { ok: QrEncodeResult } | { failure: string };

export function QrCode({ value, size = 232, caption }: QrCodeProps): ReactNode {
  const encoded = useMemo<Encoded>(() => {
    try {
      return { ok: encodeShlQr(value) };
    } catch (error) {
      return { failure: error instanceof Error ? error.message : String(error) };
    }
  }, [value]);

  if ('failure' in encoded) {
    return (
      <Callout tone="fail" title="This cannot be put in a QR code">
        <p>{encoded.failure}</p>
        <p>
          A QR symbol stops at Version 40, which is about 2,300 characters at error correction M. A
          link past that is a link whose label, viewer prefix or embedded content has to shrink; it
          is not something a bigger printout fixes.
        </p>
      </Callout>
    );
  }

  const { ok } = encoded;
  return (
    <div className="qr-block">
      <figure className="qr-figure" style={{ width: size }}>
        {/* See the header comment: the markup is machine-generated by our own
            encoder, and the custom properties only resolve when it is inline. */}
        <div className="qr-svg" dangerouslySetInnerHTML={{ __html: ok.svg }} />
        <figcaption className="qr-caption">
          {caption === undefined ? null : <span className="qr-caption-lede">{caption}</span>}
          <span className="qr-caption-meta mono">
            Version {ok.version} · {ok.modules} modules · ECC M · {ok.text.length} characters
          </span>
        </figcaption>
      </figure>
      {ok.capacity.tone === 'pass' ? null : (
        <Callout tone={ok.capacity.tone} title="Larger than the specifications aim for">
          {ok.capacity.note}
        </Callout>
      )}
    </div>
  );
}
